version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecom
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    image: myapp:latest
    container_name: springboot-app
    depends_on:
      - mysql
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_URL: jdbc:mysql://mysql:3306/ecom
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "8091:8091"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
